### ISSUE TITLE
I am using illama table in my project and now I am looking for a way to change the alternative color of the rows in the table. Is there anyway? please help.

### ISSUE THREAD

**Issue by reflections55** [luxbet/ember-cli-llama-table#16]

**Comment by j-** [comment]
This can be accomplished with CSS using the [`nth-child` selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child):

```css
.llama-body-cell:nth-child(even) {
    background-color: #eee;
}
```
